import 'package:flutter/material.dart';

class CustomIconWidget extends StatelessWidget {
  final String iconName;
  final double size;
  final Color? color;

  const CustomIconWidget({
    Key? key,
    required this.iconName,
    this.size = 24,
    this.color,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Map of available icons
    final Map<String, IconData> iconMap = {
      'analytics': Icons.analytics,
      'trending_up': Icons.trending_up,
      'local_fire_department': Icons.local_fire_department,
      'emoji_events': Icons.emoji_events,
      'water_drop': Icons.water_drop,
      'schedule': Icons.schedule,
      'notifications': Icons.notifications,
      'check_circle': Icons.check_circle,
      'check': Icons.check,
      // A
      'abc': Icons.abc,
      'ac_unit': Icons.ac_unit,
      'access_alarm': Icons.access_alarm,
      'access_alarms': Icons.access_alarms,
      'access_time': Icons.access_time,
      'access_time_filled': Icons.access_time_filled,
      'access_time_rounded': Icons.access_time_rounded,
      'accessibility': Icons.accessibility,
      'accessibility_new': Icons.accessibility_new,
      'accessible': Icons.accessible,
      'accessible_forward': Icons.accessible_forward,
      'account_balance': Icons.account_balance,
      'account_balance_wallet': Icons.account_balance_wallet,
      'account_box': Icons.account_box,
      'account_circle': Icons.account_circle,
      'account_tree': Icons.account_tree,
      'ad_units': Icons.ad_units,
      'adb': Icons.adb,
      'add': Icons.add,
      'add_a_photo': Icons.add_a_photo,
      'add_alarm': Icons.add_alarm,
      'add_alert': Icons.add_alert,
      'add_box': Icons.add_box,
      'add_business': Icons.add_business,
      'add_call': Icons.add_call,
      'add_card': Icons.add_card,
      'add_chart': Icons.add_chart,
      'add_circle': Icons.add_circle,
      'add_circle_outline': Icons.add_circle_outline,
      'add_comment': Icons.add_comment,
      'add_home': Icons.add_home,
      'add_home_work': Icons.add_home_work,
      'add_ic_call': Icons.add_ic_call,
      'add_link': Icons.add_link,
      'add_location': Icons.add_location,
      'add_location_alt': Icons.add_location_alt,
      'add_moderator': Icons.add_moderator,
      'add_photo_alternate': Icons.add_photo_alternate,
      'add_reaction': Icons.add_reaction,
      'add_road': Icons.add_road,
      'add_shopping_cart': Icons.add_shopping_cart,
      'add_task': Icons.add_task,
      'add_to_drive': Icons.add_to_drive,
      'add_to_home_screen': Icons.add_to_home_screen,
      'add_to_photos': Icons.add_to_photos,
      'add_to_queue': Icons.add_to_queue,
      'addchart': Icons.addchart,
      'adjust': Icons.adjust,
      'admin_panel_settings': Icons.admin_panel_settings,
      'adobe': Icons.adobe,
      'ads_click': Icons.ads_click,
      'agriculture': Icons.agriculture,
      'air': Icons.air,
      'airline_seat_flat': Icons.airline_seat_flat,
      'airline_seat_flat_angled': Icons.airline_seat_flat_angled,
      'airline_seat_individual_suite': Icons.airline_seat_individual_suite,
      'airline_seat_legroom_extra': Icons.airline_seat_legroom_extra,
      'airline_seat_legroom_normal': Icons.airline_seat_legroom_normal,
      'airline_seat_legroom_reduced': Icons.airline_seat_legroom_reduced,
      'airline_seat_recline_extra': Icons.airline_seat_recline_extra,
      'airline_seat_recline_normal': Icons.airline_seat_recline_normal,
      'airline_stops': Icons.airline_stops,
      'airlines': Icons.airlines,
      'airplane_ticket': Icons.airplane_ticket,
      'airplanemode_active': Icons.airplanemode_active,
      'airplanemode_inactive': Icons.airplanemode_inactive,
      'airplay': Icons.airplay,
      'airport_shuttle': Icons.airport_shuttle,
      'alarm': Icons.alarm,
      'alarm_add': Icons.alarm_add,
      'alarm_off': Icons.alarm_off,
      'alarm_on': Icons.alarm_on,
      'album': Icons.album,
      'align_horizontal_center': Icons.align_horizontal_center,
      'align_horizontal_left': Icons.align_horizontal_left,
      'align_horizontal_right': Icons.align_horizontal_right,
      'align_vertical_bottom': Icons.align_vertical_bottom,
      'align_vertical_center': Icons.align_vertical_center,
      'align_vertical_top': Icons.align_vertical_top,
      'all_inbox': Icons.all_inbox,
      'all_inclusive': Icons.all_inclusive,
      'all_out': Icons.all_out,
      'alt_route': Icons.alt_route,
      'alternate_email': Icons.alternate_email,
      'anchor': Icons.anchor,
      'android': Icons.android,
      'animation': Icons.animation,
      'announcement': Icons.announcement,
      'aod': Icons.aod,
      'apartment': Icons.apartment,
      'api': Icons.api,
      'app_blocking': Icons.app_blocking,
      'app_registration': Icons.app_registration,
      'app_settings_alt': Icons.app_settings_alt,
      'app_shortcut': Icons.app_shortcut,
      'approval': Icons.approval,
      'apps': Icons.apps,
      'apps_outage': Icons.apps_outage,
      'architecture': Icons.architecture,
      'archive': Icons.archive,
      'area_chart': Icons.area_chart,
      'arrow_back': Icons.arrow_back,
      'arrow_back_ios': Icons.arrow_back_ios,
      'arrow_back_ios_new': Icons.arrow_back_ios_new,
      'arrow_circle_down': Icons.arrow_circle_down,
      'arrow_circle_left': Icons.arrow_circle_left,
      'arrow_circle_right': Icons.arrow_circle_right,
      'arrow_circle_up': Icons.arrow_circle_up,
      'arrow_downward': Icons.arrow_downward,
      'arrow_drop_down': Icons.arrow_drop_down,
      'arrow_drop_down_circle': Icons.arrow_drop_down_circle,
      'arrow_drop_up': Icons.arrow_drop_up,
      'arrow_forward': Icons.arrow_forward,
      'arrow_forward_ios': Icons.arrow_forward_ios,
      'arrow_forward_rounded': Icons.arrow_forward_rounded,
      'arrow_left': Icons.arrow_left,
      'arrow_outward': Icons.arrow_outward,
      'arrow_right': Icons.arrow_right,
      'arrow_right_alt': Icons.arrow_right_alt,
      'arrow_upward': Icons.arrow_upward,
      'art_track': Icons.art_track,
      'article': Icons.article,
      'aspect_ratio': Icons.aspect_ratio,
      'assessment': Icons.assessment,
      'assignment': Icons.assignment,
      'assignment_ind': Icons.assignment_ind,
      'assignment_late': Icons.assignment_late,
      'assignment_return': Icons.assignment_return,
      'assignment_returned': Icons.assignment_returned,
      'assignment_turned_in': Icons.assignment_turned_in,
      'assist_walker': Icons.assist_walker,
      'assistant': Icons.assistant,
      'assistant_direction': Icons.assistant_direction,
      'assistant_photo': Icons.assistant_photo,
      'assured_workload': Icons.assured_workload,
      'atm': Icons.atm,
      'attach_email': Icons.attach_email,
      'attach_file': Icons.attach_file,
      'attach_money': Icons.attach_money,
      'attachment': Icons.attachment,
      'attractions': Icons.attractions,
      'attribution': Icons.attribution,
      'audio_file': Icons.audio_file,
      'audiotrack': Icons.audiotrack,
      'auto_awesome': Icons.auto_awesome,
      'auto_awesome_mosaic': Icons.auto_awesome_mosaic,
      'auto_awesome_motion': Icons.auto_awesome_motion,
      'auto_delete': Icons.auto_delete,
      'auto_fix_high': Icons.auto_fix_high,
      'auto_fix_normal': Icons.auto_fix_normal,
      'auto_fix_off': Icons.auto_fix_off,
      'auto_graph': Icons.auto_graph,
      'auto_mode': Icons.auto_mode,
      'auto_stories': Icons.auto_stories,
      'autofps_select': Icons.autofps_select,
      'autorenew': Icons.autorenew,
      'av_timer': Icons.av_timer,
      // ... (devamı, diğer harfler ve ikonlar) ...
      'star': Icons.star,
      'visibility': Icons.visibility,
      'share': Icons.share,
      'delete': Icons.delete,
      'camera': Icons.camera_alt,
      'lightbulb': Icons.lightbulb,
      'history': Icons.history,
      'more_vert': Icons.more_vert,
      'file_download': Icons.file_download,
      'delete_sweep': Icons.delete_sweep,
      'clear_all': Icons.clear_all,
      'settings': Icons.settings,
      'settings_applications': Icons.settings_applications,
      'settings_backup_restore': Icons.settings_backup_restore,
      'settings_bluetooth': Icons.settings_bluetooth,
      'settings_brightness': Icons.settings_brightness,
      'settings_cell': Icons.settings_cell,
      'settings_ethernet': Icons.settings_ethernet,
      'settings_input_antenna': Icons.settings_input_antenna,
      'settings_input_component': Icons.settings_input_component,
      'settings_input_composite': Icons.settings_input_composite,
      'settings_input_hdmi': Icons.settings_input_hdmi,
      'settings_input_svideo': Icons.settings_input_svideo,
      'settings_overscan': Icons.settings_overscan,
      'settings_phone': Icons.settings_phone,
      'settings_power': Icons.settings_power,
      'settings_remote': Icons.settings_remote,
      'settings_voice': Icons.settings_voice,
      'face': Icons.face,
      'brush': Icons.brush,
      'medical_services': Icons.medical_services,
      'smart_toy': Icons.smart_toy,
      'person': Icons.person,
      'done_all': Icons.done_all,
      'copy': Icons.copy,
      'bookmark': Icons.bookmark,
      'emoji_emotions': Icons.emoji_emotions,
      'mic': Icons.mic,
      'send': Icons.send,
      'spa': Icons.spa,
      'healing': Icons.healing,
      'wb_sunny': Icons.wb_sunny,
      'help_outline': Icons.help_outline,
      // ... (diğer ikonlar) ...
    };

    // Check if the icon exists
    if (iconMap.containsKey(iconName)) {
      return Icon(
        iconMap[iconName],
        size: size,
        color: color,
        semanticLabel: iconName,
      );
    } else {
      // Return a fallback icon
      return Icon(
        Icons.help_outline,
        size: size,
        color: Colors.grey,
        semanticLabel: '$iconName',
      );
    }
  }
}
